### ISSUE TITLE
Error from Hyperdash server: api_key_required

### ISSUE THREAD

**Issue by tokestermw** [hyperdashio/hyperdash-sdk-py#104]
Hi,

I can successfully run hyperdash after logging in. But it doesn't seem to be able to take the environmental variable. I'm using the api key stored in `~/.hyperdash/hyperdash.json`.

```
HYPERDASH_API_KEY = os.environ.get('HYPERDASH_API_KEY', None)


def get_api_key():
    if HYPERDASH_API_KEY:
        print(HYPERDASH_API_KEY)
        def getter():
            return HYPERDASH_API_KEY
        return getter
    else:
        return None

exp = Experiment(model_name, api_key_getter=get_api_key())
exp.end()
```

Returns an error:

```
Error from Hyperdash server: api_key_required
```

Thanks!

**Comment by richardartoul** [comment]
Thanks for finding this bug, thats our mistake. It was an easy fix: https://github.com/hyperdashio/hyperdash-sdk-py/pull/105

Just run

```bash
pip install --upgrade hyperdash
```

to upgrade to 0.12.7 and it should work now :)
