### ISSUE TITLE
invalid syntax in jupyter notebook

### ISSUE THREAD

**Issue by dtmoodie** [hyperdashio/hyperdash-sdk-py#61]
from hyperdash import monitor_cell
%%monitor_cell "test cell"

produces:

  File "<ipython-input-19-409945d38e53>", line 2
    %%monitor_cell "test cell"
    ^
SyntaxError: invalid syntax

-------------------------------------------------------------
from hyperdash import monitor_cell
%monitor_cell "test cell"

produces:

ERROR:root:Line magic function `%monitor_cell` not found (But cell magic `%%monitor_cell` exists, did you mean that instead?).

**Comment by dtmoodie** [comment]
Apparently the import call and the magic function cannot exist in the same cell.

**Comment by richardartoul** [comment]
Good catch, I'll update the README
