### ISSUE TITLE
Monitoring one Thread makes Hyperdash send all prints

### ISSUE THREAD

**Issue by North-Guard** [hyperdashio/hyperdash-sdk-py#62]
If you run multi-threaded programs and want to monitor one of them on Hyperdash (the main program for example), then Hyperdash seems to send print-statements from other threads as well. It would be nice if Hyperdash was restricted to only the monitored function. 

For example the script
```Python
import time
from threading import Thread
from hyperdash import monitor


@monitor("Hyperdash Test")
def monitored_function():
    for idx in range(10):
        print("Monitored function: {}".format(idx))
        time.sleep(1)


def non_monitored_function():
    for idx in range(10):
        print("Non-monitored function: {}".format(idx))
        time.sleep(1)


t_1 = Thread(target=monitored_function)
t_1.start()

time.sleep(1)

t_2 = Thread(target=non_monitored_function)
t_2.start()

t_1.join()
t_2.join()
```

passes the following prints to both the console and to Hyperdash

```
Monitored function: 0
Non-monitored function: 0
Monitored function: 1
Non-monitored function: 1
Monitored function: 2
Non-monitored function: 2
Monitored function: 3
Non-monitored function: 3
Monitored function: 4
Non-monitored function: 4
Monitored function: 5
Non-monitored function: 5
Monitored function: 6
Non-monitored function: 6
...
```

**Comment by richardartoul** [comment]
Hey North, thanks for the bug report!

This is interesting and an issue I hadn't thought of. Under the hood, Hyperdash is redirecting STDOUT to an IO buffer and capturing that. I don't see an easy way to limit this redirection to a specific thread because they all share an address space.

Two possible solutions:

1) We build a custom print function that you would import and use I.E  `hyperdash_print("hello world")` or something like that
2) We try and swap the existing threading model to a multiprocessing model, which would allow us to isolate stdout

I'll think about this a bit more and get back to you. Let me know if you have any other ideas on how to accomplish this!

**Comment by North-Guard** [comment]
Your welcome :)
I think the first solution would be very nice and easy to use.
That way people can direct to that print message depending on logging-level (Error, Debug etc.)

**Comment by richardartoul** [comment]
Ok cool, so to be clear your issue is not that everything is being sent to the console, your concern is that you want to isolate hyperdash print statements from the rest of your code?

I.E you want something like this

```python
import time
from threading import Thread
from hyperdash import monitor
from hyperdash import hyperdash_print


@monitor("Hyperdash Test")
def monitored_function():
    for idx in range(10):
        hyperdash_print("Monitored function: {}".format(idx))
        time.sleep(1)


def non_monitored_function():
    for idx in range(10):
        print("Non-monitored function: {}".format(idx))
        time.sleep(1)


t_1 = Thread(target=monitored_function)
t_1.start()

time.sleep(1)

t_2 = Thread(target=non_monitored_function)
t_2.start()

t_1.join()
t_2.join()
```

In that case the terminal output would still look like this:

```
Monitored function: 0
Non-monitored function: 0
Monitored function: 1
Non-monitored function: 1
Monitored function: 2
Non-monitored function: 2
Monitored function: 3
Non-monitored function: 3
Monitored function: 4
Non-monitored function: 4
Monitored function: 5
Non-monitored function: 5
Monitored function: 6
Non-monitored function: 6
```

but the actual hyperdash logs (server and local) would look like this:

```
Monitored function: 0
Monitored function: 1
Monitored function: 2
Monitored function: 3
Monitored function: 4
Monitored function: 5
Monitored function: 6
```

Is that correct?

**Comment by North-Guard** [comment]
Yes that would be perfect.

**Comment by richardartoul** [comment]
@North-Guard Take a look at this PR: https://github.com/hyperdashio/hyperdash-sdk-py/pull/69

That should solve your use-case right?

Also @andrewschreiber Can you review for interface design?

**Comment by richardartoul** [comment]
```python
# -*- coding: utf-8 -*-

import time
import sys

from hyperdash import monitor
from threading import Thread


def worker(thread_num, monitored):
    @monitor("test threading" + str(thread_num), capture_io=False)
    def monitored_func(hd_client):
        for x in range(5):
            hd_client.logger.info(
                "thread {} is doing some work".format(thread_num))
            time.sleep(1)

    def unmonitored_func():
        for x in range(5):
            print("thread {} is doing some work".format(thread_num))
            time.sleep(1)
    return monitored_func if monitored else unmonitored_func


t1 = Thread(target=worker(1, True))
t2 = Thread(target=worker(2, True))
t3 = Thread(target=worker(3, False))

t1.daemon = True
t2.daemon = True
t3.daemon = True

t1.start()
t2.start()
t3.start()

t1.join()
t2.join()
t3.join()
```

Terminal Output
```
thread 3 is doing some work
thread 1 is doing some work
thread 2 is doing some work
thread 3 is doing some work
thread 1 is doing some work
thread 2 is doing some work
thread 3 is doing some work
thread 1 is doing some work
thread 2 is doing some work
thread 3 is doing some work
thread 1 is doing some work
thread 2 is doing some work
thread 3 is doing some work
thread 2 is doing some work
thread 1 is doing some work
Logs for this run of test threading1 are available locally at: /Users/richie/.hyperdash/logs/test-threading1/test-threading1_2017-08-12t22-59-03-117036.log
Logs for this run of test threading2 are available locally at: /Users/richie/.hyperdash/logs/test-threading2/test-threading2_2017-08-12t22-59-03-119680.log
```

^^^ Each of the log files above only contains print statements from the specific thread it was assigned to and also on the mobile app I got the correct output where there were two different ones being monitored and each one only had logs for its own thread

**Comment by richardartoul** [comment]
@North-Guard I'm gonna close this because I think it works now, let me know if you have any trouble.
