### ISSUE TITLE
Delete logs from the app

### ISSUE THREAD

**Issue by miguelvr** [hyperdashio/hyperdash-sdk-py#72]
I think it would be useful if the user could simply delete some logs from the app. I'm mostly doing test runs and I'm getting a lot of useless logs that I would like to get rid off.

**Comment by spence** [comment]
@miguelvr Thanks for the feedback!

Would you like to delete the Model or clean up specific runs within a model?

**Comment by miguelvr** [comment]
both options would be nice!

**Comment by richardartoul** [comment]
@miguelvr The new version of the app with this feature is now available on the App/Play store! Long press on a specific model and a delete button should appear.

**Comment by st0le** [comment]
For any future users finding this, on Android, you need to swipe left on the Model for the delete option to appear.
