### ISSUE TITLE
Cannot use hyperdash on multiple machines.

### ISSUE THREAD

**Issue by raghakot** [hyperdashio/hyperdash-sdk-py#80]
When I try hyperdash signup from another machine, it says that the user with that email already exists. Why can't we accumulate logs from multiple machines?

**Comment by richardartoul** [comment]
Hey @raghakot you totally can! The command you're looking for is `hyperdash login` not `hyperdash signup` once you already have an account.

Let me know if that works for you!

**Comment by raghakot** [comment]
Ah thanks. Can you add this to hyperdash.io page?
