### ISSUE TITLE
web dashboard should order models based on running status

### ISSUE THREAD

**Issue by dtmoodie** [hyperdashio/hyperdash-sdk-py#89]
Currently when using the web dashboard the models seem to be sorted by the date when that model's name was originally started.
IE 
training0
training1
training2

However if I restart training with the same name, the new model training session should be bumped up the list so it is seen at the top.  That is currently not the case.

**Comment by richardartoul** [comment]
@dtmoodie Just to clarify, you're saying that on the models pages (not the runs page) you'd like to see the models sorted by those that had a run created most recently?

Also, are you available to setup a video chat? I'd love to get your feedback on Hyperdash and talk about what you're working on.

**Comment by dtmoodie** [comment]
Sorry I wrote that at the end of a long day of trying to figure out why my network wasn't converging.

Here is an example.
On day 0 I train the following networks:

net 0
net 1
net 2
net 3
net 4
net 5
net 6
net 7

They are displayed in that order on the hyperdash online dashboard in the chronological order that I started to train them.

On day 1 I then retrain net 2, net 6, and net 7; however the online dashboard still maintains the original chronological order seen above based on when the network was originally started.
So on my dashboard I have:
net 0 - complete
net 1 - complete
net 2 - training
net 3 - complete
net 4 - complete
net 5 - complete
net 6 - training
net 7 - training

When I expect the three new networks to be at the top of the dashboard since they are currently in progress.

Does that make more sense?

**Comment by richardartoul** [comment]
Got it, we'll implement that feature. The "runs" page is just what I call the page you get to after clicking on a model

**Comment by dtmoodie** [comment]
That would be awesome, thanks so much.

**Comment by richardartoul** [comment]
Done and deployed! I'm gonna close this issue, please feel free to re-open it if you have any trouble or file a new issue for other thoughts / feedback you have on the web UI

**Comment by dtmoodie** [comment]
Thanks, looks much better!
